namespace BinakayanRising.Core.Localization
{
    /// <summary>
    /// Every player-facing string in the battle slice. The text itself lives in
    /// <see cref="StringTable"/>.
    /// </summary>
    /// <remarks>
    /// Not persisted anywhere, so members may be reordered and inserted freely.
    /// <see cref="Count"/> must stay last: the table sizes its arrays from it.
    /// </remarks>
    public enum TextKey
    {
        None,

        // HUD — top bar
        HudSeed,
        HudSpeed,
        HudSkip,
        HudRedeploy,

        // HUD — phase readout
        PhaseDeployment,
        PhaseCombat,
        PhaseResolved,

        // HUD — deployment panel
        DeployTitle,
        DeployHint,
        RosterStats,
        RosterDeployed,
        SpanishColumn,
        AutoDeploy,
        BeginAssault,
        ShowTips,
        HideTips,
        TipsBody,

        // HUD — combat panel
        OrderOfBattle,
        TeamKatipunan,
        TeamSpanish,
        FieldReport,

        // HUD — outcome card
        OutcomeVictory,
        OutcomeDefeat,
        OutcomeDraw,
        OutcomeTurns,
        OutcomeSurvivors,
        OutcomeSeed,
        NewSeed,

        // Unit names
        UnitMarksman,
        UnitEngineer,
        UnitEvangelista,
        UnitAguinaldo,
        UnitVanguard,
        UnitSpanishRegular,

        // Field report and floating numbers
        LogAssaultBegan,
        LogRouted,
        LogCriticalHit,
        LogResolved,
        PopupDodge,
        PopupMiss,

        // Guided tutorial
        TutNext,
        TutSkip,
        TutDone,
        TutStep,
        TutWelcomeTitle,
        TutWelcomeBody,
        TutPickTitle,
        TutPickBody,
        TutPlaceTitle,
        TutPlaceBody,
        TutTerrainTitle,
        TutTerrainBody,
        TutBondsTitle,
        TutBondsBody,
        TutAutoTitle,
        TutAutoBody,
        TutAssaultTitle,
        TutAssaultBody,
        TutWatchTitle,
        TutWatchBody,
        TutOutcomeTitle,
        TutOutcomeBody,

        // How-to-Play deck
        DeckTitle,
        DeckBack,
        DeckNext,
        DeckClose,
        DeckReplay,
        DeckBattleTitle,
        DeckBattleBody,
        DeckDeployTitle,
        DeckDeployBody,
        DeckUnitsTitle,
        DeckUnitsBody,
        DeckTerrainTitle,
        DeckTerrainBody,
        DeckBondsTitle,
        DeckBondsBody,
        DeckCombatTitle,
        DeckCombatBody,
        DeckControlsTitle,
        DeckControlsBody,
        TerrainTrench,
        TerrainTent,
        TerrainShallows,
        TerrainBamboo,

        // Shared buttons
        CommonConfirm,
        CommonCancel,
        CommonClose,
        CommonBack,
        CommonOn,
        CommonOff,

        // Main menu
        MenuTagline,
        MenuContinue,
        MenuNewCampaign,
        MenuSettings,
        MenuQuit,
        MenuSaveSummary,
        MenuOverwriteTitle,
        MenuOverwriteBody,
        MenuSaveRestored,

        // Settings
        SetTitle,
        SetAudio,
        SetMusic,
        SetSfx,
        SetMute,
        SetDisplay,
        SetResolution,
        SetFullscreen,
        SetLanguageText,
        SetLanguage,
        SetTextSpeed,
        SetSaveTutorial,
        SetReplayTutorial,
        SetReplayDone,
        SetDeleteSave,
        SetDeleteTitle,
        SetDeleteBody,
        SetNoSave,
        LangEnglish,
        LangFilipino,
        SpeedSlow,
        SpeedNormal,
        SpeedFast,
        SpeedInstant,

        // Encampment chrome
        HubMenu,
        HubObjective,
        HubRank,
        CurReales,
        CurRations,
        CurScrap,
        HubToTitle,
        HubSaved,
        HubQuestDone,
        HubRewardReales,
        HubComingSoon,
        HubNoPath,
        DlgNext,
        DlgSkip,
        DlgHint,
        ResStored,
        ResNext,
        ResFull,
        ResHarvest,
        ResNothing,
        ResGot,
        ResRate,
        ResBack,
        ExLot,
        ExHave,
        ExSellOne,
        ExSellAll,
        ExSold,
        ExShort,
        InvResources,
        InvWeapons,
        InvRealesUse,
        InvRationsUse,
        InvScrapUse,
        InvWhere,
        InvHeldBy,
        InvOnRack,
        InvAttack,
        InvTier,
        InvGiveTo,
        InvReforge,
        InvReforgeInto,
        InvTopTier,
        InvNone,
        InvPick,
        InvEquipped,
        InvReforged,
        InvCantAfford,
        TrnLevel,
        TrnXp,
        TrnTopLevel,
        TrnHealth,
        TrnAttack,
        TrnDefense,
        TrnNow,
        TrnNext,
        TrnWeapon,
        TrnNoWeapon,
        TrnDrill,
        TrnDrillGives,
        TrnDrilled,
        TrnKeeperNote,
        TrnPage,
        PromoTitle,
        PromoLevel,
        RecRates,
        RecPity,
        RecPityNext,
        RecDuplicate,
        RecOne,
        RecTen,
        RecCost,
        RecSave,
        RecIntro,
        RecResults,
        RecNew,
        RecDupXp,
        RecGuaranteed,
        RecCantAfford,
        RecTapToReveal,
        RecRevealAll,
        RecRoster,

        // Campaign battles
        HudSquad,
        MissionReturn,
        MissionRetreat,
        OutcomeHeld,
        MissionWonNote,
        MissionLostNote,
        MissionRetreated,
        MissionLostToast,
        RankUpTitle,
        RankUpStep,
        CutNext,
        CutSkip,
        CutDone,
        MapTitle,
        MapLevel,
        MapEnemies,
        MapSquad,
        MapWinRout,
        MapWinHold,
        MapCost,
        MapReward,
        MapRewardLesson,
        MapDeploy,
        MapReplay,
        MapLocked,
        MapCleared,
        MapInCamp,
        MapNoRations,
        MapComplete,
        QuizTitle,
        QuizProgress,
        QuizRight,
        QuizWrong,
        QuizReales,
        LibTitle,
        LibLocked,
        LibTest,
        LibTestLocked,
        LibTestReady,
        LibBest,
        LibPassed,
        LibResult,
        LibFirstPass,
        LibFail,
        HudMinimap,
        LibLockedShort,
        PauseTitle,
        PauseResume,
        PauseHint,
        TrnStatHp,
        TrnStatAtk,
        TrnStatDef,
        TrnStatEva,
        TrnStatAcc,
        TrnStatRng,
        TrnStatCrit,
        TrnStatMove,
        TrnStatHeal,
        TrnBond,
        TrnNoBond,
        DeckMoreUnitsTitle,
        DeckMoreUnitsBody,

        // #12 drag-and-drop deployment, #22 panels hidden during the replay
        DeployStripHint,

        // Agent D: splash (#46), glossary (#50).
        SplashPressAnyKey,
        LibTabLessons,
        LibTabGlossary,
        LibGlossaryPage,
        LibGlossaryNote,

        // #16 Spanish roster, #37 Escort, #38 Sabotage (agent A).
        UnitSpanishArtillery,
        UnitSpanishCazador,
        UnitSpanishOfficer,
        UnitSpanishMarine,
        UnitSupplyCart,
        HudObjectiveEscort,
        HudObjectiveSabotage,
        MapWinEscort,
        MapWinSabotage,
        OutcomeCartSaved,
        OutcomeCartLost,
        OutcomeMagazineBlown,
        OutcomeMagazineMissed,
        DeckEnemiesTitle,
        DeckEnemiesBody,

        // #43 Tactician's Command, #19 Kapatiran ranks, #20 Kapatiran lore
        CmdTitle,
        CmdPrompt,
        CmdHeal,
        CmdHealHint,
        CmdAttack,
        CmdAttackHint,
        CmdReset,
        CmdResetHint,
        CmdRevive,
        CmdReviveHint,
        CmdReviveNone,
        CmdIssued,
        LogCmdHeal,
        LogCmdAttack,
        LogCmdReset,
        LogCmdRevive,
        PopupAttack,
        BondTitle,
        BondRankStep,
        BondNoBonus,
        BondBonus,
        BondLoreUnlocked,
        BondListen,
        BondNoBonusShort,
        TrnBondRanked,
        LoreTitle,
        LoreButton,
        LoreLocked,
        LoreSupport,
        LoreNew,
        LoreClose,

        Count
    }
}
